# /config_actions.py
"""
Configuration constants defining input action identifiers.
"""

# Input Actions (returned by InputHandler)
ACTION_QUIT = "QUIT"
ACTION_DEAL_DRAW = "DEAL_DRAW"
ACTION_PLAY_AGAIN = "PLAY_AGAIN"
# Top Menu Actions
ACTION_GOTO_PLAY = "GOTO_PLAY"
ACTION_GOTO_SETTINGS = "GOTO_SETTINGS"
# Game Selection Actions
ACTION_CHOOSE_DRAW_POKER = "CHOOSE_DRAW_POKER"
ACTION_CHOOSE_MULTI_POKER = "CHOOSE_MULTI_POKER"
ACTION_CHOOSE_BLACKJACK = "CHOOSE_BLACKJACK"
ACTION_CHOOSE_ROULETTE = "CHOOSE_ROULETTE"
ACTION_CHOOSE_SLOTS = "CHOOSE_SLOTS"
ACTION_CHOOSE_BACCARAT = "CHOOSE_BACCARAT"
ACTION_RESTART_GAME = "RESTART_GAME"
ACTION_RETURN_TO_MENU = "RETURN_TO_MENU"
ACTION_HOLD_TOGGLE = "HOLD_TOGGLE" # Payload will be the index (0-4)
# Settings Actions
ACTION_TOGGLE_SOUND = "TOGGLE_SOUND"
ACTION_RETURN_TO_TOP_MENU = "RETURN_TO_TOP_MENU" # From Settings
ACTION_VOLUME_UP = "VOLUME_UP"
ACTION_VOLUME_DOWN = "VOLUME_DOWN"
# Confirmation Actions
ACTION_CONFIRM_YES = "CONFIRM_YES"
ACTION_CONFIRM_NO = "CONFIRM_NO"
# Blackjack Actions
ACTION_BLACKJACK_HIT = "BLACKJACK_HIT"
ACTION_BLACKJACK_STAND = "BLACKJACK_STAND"
# Roulette Actions
ACTION_ROULETTE_BET = "ROULETTE_BET" # Payload will be bet details dict
ACTION_ROULETTE_SPIN = "ROULETTE_SPIN"
ACTION_ROULETTE_CLEAR_BETS = "ROULETTE_CLEAR_BETS"
# Slots Actions
ACTION_SLOTS_SPIN = "SLOTS_SPIN"
# Baccarat Actions
ACTION_BACCARAT_BET = "BACCARAT_BET" # Payload: {'type': BET_PLAYER/BET_BANKER/BET_TIE}
ACTION_BACCARAT_DEAL = "BACCARAT_DEAL"
ACTION_BACCARAT_CLEAR_BETS = "BACCARAT_CLEAR_BETS"
